{% set name = "wordfreq" %}
{% set version = "3.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wordfreq-{{ version }}.tar.gz
  sha256: 7943098975f25c2a70e1151ee5a62083b14a5f86f6cc5703cc9526f716ceb408

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - ftfy >=6.1
    - langcodes >=3.0
    - msgpack-python >=1.0
    - mypy >=0.931,<0.932
    - python >=3.7
    - regex >=2020.04.04

test:
  imports:
    - wordfreq
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/LuminosoInsight/wordfreq/
  summary: Python library for looking up the frequencies of words in many languages.
  license: MIT
  license_file: MIT-LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
